###
GET http://localhost:3000/api/clients

###
GET http://localhost:3000/api/clients/2

###
POST http://localhost:3000/api/clients
Content-Type: application/json

{
    "name": "María",
    "surname": "Camacho",
    "address": "Bota 89",
    "phone": "669323210",
    "birthdate": "1997-10-7",
    "email": "marCam@mail.com",
    "dni": "34129091"
}

###
PUT http://localhost:3000/api/clients/13
Content-Type: application/json

{
   "name": "Daniel",
    "surname": "Pozo",
    "address": "Rodrigo 5",
    "phone": "755190162",
    "birthdate": "1999-09-12",
    "email": "danPoz@mail.com",
    "dni": "33897456"
}

###
DELETE http://localhost:3000/api/clients/3